import { salesConfig } from "./salesConfig";

export const products = [
  {
    name: "Máy xúc điều khiển từ xa YIGONG",
    model: "11 kênh, gầu hợp kim, tỉ lệ 1:20",
    price: "359.000đ - 409.000đ",
    schemaPrice: "359000",
    rating: "4.9",
    sold: "664 đã bán",
    reviews: "384 đánh giá",
    image: "/assets/products/xuc-yigong.webp",
    badge: "Bán chạy",
    highlights: ["2.4GHz", "Gầu hợp kim", "Mô phỏng chân thực"],
    href: `${salesConfig.shopUrl}?keyword=m%C3%A1y%20x%C3%BAc%20yigong`,
  },
  {
    name: "Xe tải điều khiển từ xa XUEZHISHAN",
    model: "Thùng hợp kim nâng 65 độ, tỉ lệ 1:20",
    price: "569.000đ",
    schemaPrice: "569000",
    rating: "4.9",
    sold: "156 đã bán",
    reviews: "52 đánh giá",
    image: "/assets/products/ben-xuezhishan.webp",
    badge: "Thùng nâng 65 độ",
    highlights: ["Điều khiển từ xa", "Chi tiết sắc nét", "Quà tặng hấp dẫn"],
    href: `${salesConfig.shopUrl}?keyword=xuezhishan%20xe%20t%E1%BA%A3i`,
  },
  {
    name: "Xe ủi điều khiển từ xa YIGONG",
    model: "9 kênh, gầu hợp kim, tỉ lệ 1:20",
    price: "369.000đ",
    schemaPrice: "369000",
    rating: "4.9",
    sold: "142 đã bán",
    reviews: "51 đánh giá",
    image: "/assets/products/ui-yigong.webp",
    badge: "Gầu hợp kim",
    highlights: ["9 chức năng", "Hỏa tốc", "Bảo hành uy tín"],
    href: `${salesConfig.shopUrl}?keyword=xe%20%E1%BB%A7i%20yigong`,
  },
  {
    name: "Xe tải điều khiển từ xa YIGONG",
    model: "9 kênh, thùng hợp kim nâng 45 độ, tỉ lệ 1:20",
    price: "309.000đ",
    schemaPrice: "309000",
    rating: "4.8",
    sold: "306 đã bán",
    reviews: "124 đánh giá",
    image: "/assets/products/ben-yigong.webp",
    badge: "Giá tốt",
    highlights: ["9 chức năng", "Thùng nâng", "Giao hỏa tốc"],
    href: `${salesConfig.shopUrl}?keyword=yigong%20xe%20t%E1%BA%A3i`,
  },
  {
    name: "Máy xúc điều khiển từ xa XUEZHISHAN",
    model: "11 kênh, gầu hợp kim, tỉ lệ 1:20",
    price: "789.000đ",
    schemaPrice: "789000",
    rating: "5.0",
    sold: "170 đã bán",
    reviews: "73 đánh giá",
    image: "/assets/products/xuc-xuezhishan.webp",
    badge: "Cao cấp",
    highlights: ["11 kênh", "Phụ kiện đi kèm", "Quà sinh nhật cho bé"],
    href: `${salesConfig.shopUrl}?keyword=m%C3%A1y%20x%C3%BAc%20xuezhishan`,
  },
];
